admin/files: add test which is expected to fail
Adds test replicating the user's issue and is added now to confirm wether this is indeed an issue and wether my fix actually works.

Good, it fails.

```
FAILED authentik/admin/files/backends/tests/test_s3_backend.py::TestS3Backend::test_file_url_custom_domain_with_bucket_no_duplicate - AssertionError: 2 != 1 : Bucket name 'authentik-test-270gxfe1t2' appears 2 times in URL, expected 1. URL: https://localhost:8020/authentik-test-270gxfe1t2/authentik-test-270gxfe1t2/media/public/application-icons/test.svg?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=accessKey1%2F20260117%2Fca-central-1%2Fs3%2Faws4_request&X-Amz-Date=20260117T010127Z&X-Amz-Expires=900&X-Amz-SignedHeaders=host&X-Amz-Signature=b24c140b41232df1d0c7d51197d6a94d59b09bcc8fbe31de54be92e34b61f65b
```